#!/bin/bash
if [ $# -eq 0 ]
then
        echo "Usage: phone searchfor [...searchfor]"
        echo "(You didn't tell me what you want to search for.)"
else
        str=""
        for arg in $*
        do
                if [ -z $str ]
                then
                        str="$arg"
                else
                        str="$str|$arg"
                fi
        done
        str="($str)"
        egrep "$str" mydata | awk -f display.awk
              
fi         
